# Google Cloud Run Deployment Configuration
# Connects to external MySQL Docker database

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: haustap-api
  annotations:
    run.googleapis.com/execution-environment: gen2
    run.googleapis.com/cpu-throttling: "false"
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu: "2"
        run.googleapis.com/memory: "2Gi"
        run.googleapis.com/max-instances: "100"
        run.googleapis.com/min-instances: "1"
        autoscaling.knative.dev/maxScale: "100"
    spec:
      containerConcurrency: 1000
      containers:
      - name: haustap-api
        image: gcr.io/YOUR-PROJECT-ID/haustap-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: APP_ENV
          value: "production"
        - name: APP_DEBUG
          value: "false"
        - name: APP_URL
          value: "https://haustap-api-abc123-uc.a.run.app"
        - name: DB_CONNECTION
          value: "mysql"
        - name: DB_HOST
          value: "YOUR_MYSQL_HOST_IP"  # Your Docker MySQL host IP
        - name: DB_PORT
          value: "3307"
        - name: DB_DATABASE
          value: "haustap_db"
        - name: DB_USERNAME
          value: "haustap_user"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: password
        - name: CACHE_STORE
          value: "database"
        - name: SESSION_DRIVER
          value: "database"
        - name: QUEUE_CONNECTION
          value: "database"
        - name: LOG_CHANNEL
          value: "stderr"
        - name: LOG_LEVEL
          value: "info"
        - name: FRONTEND_URL
          value: "https://your-frontend-url.com"
        - name: MOBILE_APP_URL
          value: "https://your-mobile-url.com"
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-password
type: Opaque
data:
  password: aGF1c3RhcF9wYXNzd29yZA==  # base64 encoded password